export const PHOTO_PICK_REQUEST = 'PHOTO_PICK_REQUEST';
export const PHOTO_PICK_SUCCESS = 'PHOTO_PICK_SUCCESS';
export const PHOTO_PICK_FAILURE = 'PHOTO_PICK_FAILURE';

export const PHOTO_UPLOAD_REQUEST = 'PHOTO_UPLOAD_REQUEST';
export const PHOTO_UPLOAD_SUCCESS = 'PHOTO_UPLOAD_SUCCESS';
export const PHOTO_UPLOAD_FAILURE = 'PHOTO_UPLOAD_FAILURE';
