export const PLANTS_ADD_REQUEST = 'PLANTS_ADD_REQUEST';
export const PLANTS_ADD_SUCCESS = 'PLANTS_ADD_SUCCESS';
export const PLANTS_ADD_FAILURE = 'PLANTS_ADD_FAILURE';

export const PLANTS_DELETE_REQUEST = 'PLANTS_DELETE_REQUEST';
export const PLANTS_DELETE_SUCCESS = 'PLANTS_DELETE_SUCCESS';
export const PLANTS_DELETE_FAILURE = 'PLANTS_DELETE_FAILURE';

export const PLANTS_GET_REQUEST = 'PLANTS_GET_REQUEST';
export const PLANTS_GET_SUCCESS = 'PLANTS_GET_SUCCESS';
export const PLANTS_GET_FAILURE = 'PLANTS_GET_FAILURE';

export const PLANTS_REFRESH_REQUEST = 'PLANTS_REFRESH_REQUEST';
export const PLANTS_REFRESH_SUCCESS = 'PLANTS_REFRESH_SUCCESS';
export const PLANTS_REFRESH_FAILURE = 'PLANTS_REFRESH_FAILURE';
