export const PLANT_GET_POSTS_REQUEST = 'PLANT_GET_POSTS_REQUEST';
export const PLANT_GET_POSTS_SUCCESS = 'PLANT_GET_POSTS_SUCCESS';
export const PLANT_GET_POSTS_FAILURE = 'PLANT_GET_POSTS_FAILURE';

export const PLANT_ADD_POST_REQUEST = 'PLANT_ADD_POST_REQUEST';
export const PLANT_ADD_POST_SUCCESS = 'PLANT_ADD_POST_SUCCESS';
export const PLANT_ADD_POST_FAILURE = 'PLANT_ADD_POST_FAILURE';

export const PLANT_CLEAR_POSTS = 'PLANT_CLEAR_POSTS';
