export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAILURE = 'POSTS_GET_FAILURE';

export const POSTS_REFRESH_REQUEST = 'POSTS_REFRESH_REQUEST';
export const POSTS_REFRESH_SUCCESS = 'POSTS_REFRESH_SUCCESS';
export const POSTS_REFRESH_FAILURE = 'POSTS_REFRESH_FAILURE';
